### ISSUE TITLE
Webcam

### ISSUE THREAD

**Issue by geadalfa** [img88/ALPR-IndonesiaPlateNumber#2]
Halo, programnya sangat bagus dan akurat mas, saya ingin tanya bagaimana cara untuk mendeteksi plat langsung dari webcam laptop?

**Comment by img88** [comment]
> Halo, programnya sangat bagus dan akurat mas, saya ingin tanya bagaimana cara untuk mendeteksi plat langsung dari webcam laptop?

Bisa tapi tidak secara realtime ya, jadi bisa buat terlebih dahulu program capture gambar lewat webcam, nanti hasil capture dimasukan ke program ALPR nya, maaf baru dibalas baru kebaca 😃
